kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: ingress-nginx-static-files  
  namespace: mfuste   
  labels:  
    app: ingress-nginx   
data:  
  index.html: |  
    <!doctype html>  
    <html>  
      <head>  
        <meta charset="utf-8">  
        <title>Això és un ConfigMap</title>  
        <link rel="stylesheet" href="main.css">  
      </head>  
      <body>  
        <h1>Hola hola nginx</h1>
      </body>  
    </html>  
  main.css: |  
    body {  
      background-color: lightgray;  
      font-family: Verdana, Arial, Helvetica, sans-serif;  
    }    
---  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  labels:  
    app: ingress-nginx   
  name: ingress-nginx  
  namespace: mfuste 
spec:  
  selector:  
    matchLabels:  
      app: ingress-nginx  
  replicas: 1  
  template:  
    metadata:  
      labels:  
        app: ingress-nginx    
      name: ingress-nginx  
    spec:  
      containers:  
        - name: ingress-nginx  
          image: nginx:1.19.6   
          imagePullPolicy: Always  
          resources:  
            limits:  
              cpu: 100m  
              memory: 10Mi  
            requests:  
              cpu: 100m  
              memory: 10Mi  
          volumeMounts:  
            - readOnly: true  
              mountPath: /usr/share/nginx/html
              name: html-files  
      volumes:  
        - name: html-files  
          configMap:  
            name: ingress-nginx-static-files  
---  
kind: Service  
apiVersion: v1  
metadata:  
  name: ingress-nginx  
  namespace: mfuste  
  labels:  
    app: ingress-nginx  
spec:  
  selector:  
    app: ingress-nginx  
  ports:  
  - name: http  
    protocol: TCP  
    port: 80  
    targetPort: 8080  
---  
apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: nginx-ingress  
  namespace: mfuste
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /  
    kubernetes.io/ingress.class: "nginx"    
  labels:  
    app: ingress-nginx  
spec:  
  rules:  
  - http:  
      paths:  
      - path: /  
        backend:  
          serviceName: ingress-nginx  
          servicePort: 80